function getEl() {
  const el = {
    auth: document.querySelectorAll('.auth'),
    body: document.querySelector('#page-container'),
    header: {
      bar: document.querySelector('.nav-bar'),
      nav: document.querySelector('#nav-sidebar-button'),
      logo: document.querySelector('#peerview-logo'),
      search: document.querySelector('#nav-search'),
      notif: document.querySelector('#notif-sidebar-button'),
    },
    nav: {
      bar: document.querySelector('#nav-sidebar'),
      signin: document.querySelector('.g-signin2'),
      signout: document.querySelector('#nav-signout'),
      upload: document.querySelector('#nav-sidebar-upload'),
      recent: document.querySelector('#nav-sidebar-recent'),
      pubs: document.querySelector('#nav-sidebar-user-pubs'),
      cohort: document.querySelector('#nav-sidebar-cohorts'),
      account: document.querySelector('#nav-sidebar-account'),
      about: document.querySelector('#nav-sidebar-about'),
      theme: document.querySelector('#nav-sidebar-theme'),
    },
    notif: {
      bar: document.querySelector('#notif-sidebar'),
      refresh: document.querySelector('#notif-refresh'),
      list: document.querySelector('#notif-list'),
      offset: document.querySelector('#notif-offset'),
    },
    pubInspect: {
      page: document.querySelector('#pub-inspect'),
      auth: document.querySelectorAll('#pub-inspect .auth'),
      title: document.querySelector('#pub-title'),
      disp: document.querySelector('#pub-user-display'),
      download: document.querySelector('#pub-download'),
      of5: document.querySelector('#pub-of5'),
      cohort: document.querySelector('#pub-cohort'),
      area: document.querySelector('#pub-area'),
      abstract: document.querySelector('#pub-abstract'),
      citation: document.querySelector('#pub-citation-container'),
      reviewInput: document.querySelector('#review-input'),
      reviewList: document.querySelector('#pub-review-list-container'),
      reviewOffset: document.querySelector('#pub-review-list-offset'),
      edit: document.querySelector('#pub-edit-button'),
      reviewCont: document.querySelector('#pub-review-container'),
      reviewOf5: document.querySelector('#review-of5'),
      reviewSubmit: document.querySelector('#review-submit'),
    },
    pubManage: {
      page: document.querySelector('#pub-manage'),
      title: document.querySelector('#pub-title-input'),
      area: document.querySelector('#pub-area-input'),
      cohort: document.querySelector('#pub-cohort-input'),
      abstract: document.querySelector('#pub-abstract-input'),
      citationList: document.querySelector('#pub-citation-input-list'),
      citationText: document.querySelector('#pub-citation-text-input'),
      citationLink: document.querySelector('#pub-citation-link-input'),
      link: document.querySelector('#pub-link-input'),
      citationAdd: document.querySelector('#citation-add-button'),
      fileButton: document.querySelector('#pub-pdf-input-button'),
      fileCheck: document.querySelector('#pub-check-file'),
      linkCheck: document.querySelector('#pub-check-link'),
      fileInput: document.querySelector('#pub-pdf-input'),
      submit: document.querySelector('#pub-info-save'),
      delete: document.querySelector('#pub-delete'),
    },
    cohortInspect: {
      page: document.querySelector('#cohort-inspect'),
      edit: document.querySelector('#cohort-edit-button'),
      name: document.querySelector('#cohort-name'),
      avatar: document.querySelector('#cohort-avatar'),
      birthday: document.querySelector('#cohort-birthday'),
      admin: document.querySelector('#cohort-admin'),
      desc: document.querySelector('#cohort-desc'),
      users: document.querySelector('#cohort-user-info'),
      pubs: document.querySelector('#cohort-pub-info'),
      auth: document.querySelectorAll('#cohort-inspect .auth'),
    },
    cohortManage: {
      page: document.querySelector('#cohort-manage'),
      avatar: document.querySelector('#cohort-avatar-input'),
      name: document.querySelector('#cohort-name-input'),
      desc: document.querySelector('#cohort-desc-input'),
      users: document.querySelector('#cohort-user-manage'),
      pubs: document.querySelector('#cohort-pubs-manage'),
      avatarButton: document.querySelector('#change-cohort-avatar-button'),
      avatarUpload: document.querySelector('#change-cohort-avatar-input'),
      delete: document.querySelector('#cohort-delete-button'),
      submit: document.querySelector('#cohort-save-button'),
    },
    userInspect: {
      page: document.querySelector('#user-inspect-page'),
      auth: document.querySelectorAll('#user-inspect-page .auth'),
      disp: document.querySelector('#user-disp-name'),
      inviteList: document.querySelector('#cohort-invite-list'),
      avatar: document.querySelector('#user-avatar'),
      name: document.querySelector('#user-name'),
      email: document.querySelector('#user-email'),
      about: document.querySelector('#user-about'),
      pubs: document.querySelector('#user-pubs'),
      cohorts: document.querySelector('#user-cohorts'),
      edit: document.querySelector('#user-edit'),
      inviteSubmit: document.querySelector('#cohort-invite-button'),
    },
    userManage: {
      page: document.querySelector('#user-manage-page'),
      avatar: document.querySelector('#user-avatar-input'),
      disp: document.querySelector('#user-disp-input'),
      fname: document.querySelector('#user-fname-input'),
      lname: document.querySelector('#user-lname-input'),
      email: document.querySelector('#user-email-input'),
      about: document.querySelector('#user-about-input'),  
      avatarUpload: document.querySelector('#change-user-avatar-input'),
      avatarButton: document.querySelector('#change-user-avatar-button'),
      submit: document.querySelector('#user-save'),
      delete: document.querySelector('#user-delete'),
    },
    search: {
      page: document.querySelector('#search-page'),
      cohort: document.querySelector('#search-cohort'),
      user: document.querySelector('#search-user'),
      pub: document.querySelector('#search-pub'),
      bar: document.querySelector('#search-bar'),
      go: document.querySelector('#search-go'),
      results: document.querySelector('#search-results'),
      offset: document.querySelector('#search-offset'),
    },
    feed: {
      page: document.querySelector('#feed-page'),
      results: document.querySelector('#feed-results'),
      offset: document.querySelector('#feed-offset'),
    },
    your: {
      page: document.querySelector('#your-page'),
      auth: document.querySelectorAll('#your-page .auth'),
      cohort: document.querySelector('#new-cohort'),
      pub: document.querySelector('#new-pub'),
      list: document.querySelector('#your-list'),
    },
    about: {
      page: document.querySelector('#about-page'),
    },
    error: {
      page: document.querySelector('#error-page'),
      button: document.querySelector('#error-button'),
    },
    templates: {
      notif: document.querySelector('#notif-template'),
      citation: document.querySelector('#citation-template'),
      review: document.querySelector('#review-template'),
      comment: document.querySelector('#comment-template'),
      list: document.querySelector('#list'),
      feed: document.querySelector('#feed-template'),
      result: document.querySelector('#result-template'),
    },
  };
  return el;
}

export { getEl };